version: "3.8"
services:
  app:
    container_name: blog-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://db:27017/Blogger
    depends_on:
      - mongo
    volumes:
      - ./:/app
    networks:
      - app-network
  mongo:
    container_name: mongo-db
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb-data:/data/db
    command: mongod --port 27017 --dbpath /data/db
    networks:
      - app-network

volumes:
  mongodb-data:

networks:
  app-network: