version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27018:27017
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://db:27017/blogger
    restart: always
    depends_on:
      - mongodb
